import { LevelConfig } from "@/types";
import { generateWavesForLevel } from "./WaveGenerator";

export const TOTAL_LEVELS = 10;

export const LEVEL_CONFIGS: LevelConfig[] = [
  {
    level: 1,
    name: "Forest Clearing",
    rows: 8,
    cols: 12,
    minPathLength: 14,
    startingGold: 120,
    startingLives: 25,
    waves: generateWavesForLevel(1),
    seed: 42,
  },
  {
    level: 2,
    name: "River Crossing",
    rows: 10,
    cols: 14,
    minPathLength: 18,
    startingGold: 100,
    startingLives: 20,
    waves: generateWavesForLevel(2),
    seed: 137,
  },
  {
    level: 3,
    name: "Mountain Pass",
    rows: 10,
    cols: 16,
    minPathLength: 22,
    startingGold: 100,
    startingLives: 20,
    waves: generateWavesForLevel(3),
    seed: 256,
  },
  {
    level: 4,
    name: "Dark Swamp",
    rows: 12,
    cols: 16,
    minPathLength: 26,
    startingGold: 90,
    startingLives: 18,
    waves: generateWavesForLevel(4),
    seed: 512,
  },
  {
    level: 5,
    name: "Frozen Wastes",
    rows: 12,
    cols: 18,
    minPathLength: 28,
    startingGold: 80,
    startingLives: 15,
    waves: generateWavesForLevel(5),
    seed: 777,
  },
  {
    level: 6,
    name: "Dragon's Gate",
    rows: 14,
    cols: 20,
    minPathLength: 32,
    startingGold: 80,
    startingLives: 12,
    waves: generateWavesForLevel(6),
    seed: 1024,
  },
  {
    level: 7,
    name: "Sky Fortress",
    rows: 14,
    cols: 20,
    minPathLength: 34,
    startingGold: 100,
    startingLives: 15,
    waves: generateWavesForLevel(7),
    seed: 1337,
  },
  {
    level: 8,
    name: "Cursed Depths",
    rows: 16,
    cols: 22,
    minPathLength: 38,
    startingGold: 100,
    startingLives: 12,
    waves: generateWavesForLevel(8),
    seed: 2048,
  },
  {
    level: 9,
    name: "Shadow Realm",
    rows: 16,
    cols: 24,
    minPathLength: 42,
    startingGold: 110,
    startingLives: 10,
    waves: generateWavesForLevel(9),
    seed: 3141,
  },
  {
    level: 10,
    name: "Final Bastion",
    rows: 18,
    cols: 26,
    minPathLength: 46,
    startingGold: 120,
    startingLives: 10,
    waves: generateWavesForLevel(10),
    seed: 9999,
  },
];
